Repository superDeano/Register-and-Share, pull requests merged in 2020-12, with the labels that each got.

#5 my first commit
  src/server/Server.java
Labels: enhancement

#6 server switch
  Register-and-Share.iml
  src/server/Main.java
  src/server/Server.java
Labels: enhancement

#7 ability for server to display the other server information automatically and save other's info; save for the client
  src/client/Client.java
  src/client/RssClient.java
  src/dao/ServerStorage.java
  src/server/Main.java
  src/server/Server.java
Labels: feature

#8 added checks in queries that only current server can access/update/insert required data in db
  src/dao/ServerStorage.java
Labels: enhancement, feature, server

#9 Sever switching fixes
  src/client/CliClient.java
  src/client/Client.java
  src/client/ClientInterface.java
  src/client/RssClient.java
  src/communication/Communication.java
  src/dao/ServerStorage.java
  src/dao/ServerStorageInterface.java
  src/message/Message.java
  src/message/MsgType.java
  src/message/Parsing.java
  src/server/Main.java
  src/server/Server.java
Labels: enhancement
